### ISSUE TITLE
PS4 Always marked as "on" when in standby

### ISSUE THREAD

**Issue by MarkieMark96** [dhleong/ps4-waker#106]
I currently have this working to turn on the PS4, however the PS4 is always marked as "on" in the Home app 24/7 even when not actually on.

When I open a separate CMD prompt and enter "ps4-waker -b <interface.ip> search  grep -i '200 Ok" I get results back that show the PS4 is in Standby mode however whilst Homebridge is running and constantly checking this status it is saying "[CMD Switch] Playstation 4 Pro is on."

"<interface.ip>" is replaced with the IP address of the network interface on my computer

Below is the config inside my config.json file

"platform": "cmdSwitch2",
		"name": "CMD Switch",
		"switches": [{
			"name": "Playstation 4 Pro",
			"on_cmd": "ps4-waker -b <interface.ip>",
			"off_cmd": "ps4-waker -b <interface.ip> standby",
			"state_cmd": "ps4-waker -b <interface.ip> search  grep -i '200 Ok'",
			"polling": true,
			"interval": 5,
			"timeout": 2000,
			"manufacturer": "Sony Corporation",
			"model": "PS4",
			"serial": "PS4"

Any help is appreciated to determine if User error or bug.

**Comment by dhleong** [comment]
Your `state_cmd` is wrong. It should look like:

    ps4-waker -b <interface.ip> search | grep -i '200 Ok'

Note the `|` character. That's called a "pipe" and it "pipes" the output of the first command into the second. In this case, you need it to pass the output from the search command (the PS4 status) to the `grep` command, which searches that output for `200 Ok`. Without the pipe, it will always be successful, since you always have a PS4 on the network.

**Comment by MarkieMark96** [comment]
When using the pipe I receive back an error

"'grep' is not recognized as an internal or external command,
operable program or batch file."

Hence nothing worked, then when searching online unrelated to ps4-waker there was a suggestion for removing the pipe and having it work.

I should have mentioned this as the reason why the pipe wasn't there, my apologies.

**Comment by dhleong** [comment]
Without the pipe, `grep` will never actually be run, so it is definitely necessary. But it sounds like you don't have `grep`, which is the real problem here. Are you using a raspberry pi or something? Most Linux machines come with `grep`, but if you don't have it you'll have to look up how to install it for your specific machine.

**Comment by MarkieMark96** [comment]
Running 

ps4-waker -b 10.0.0.31 search | findstr -i '200 ok

I get back "FINDSTR: Cannot open ok" if that helps

**Comment by dhleong** [comment]
See: https://stackoverflow.com/questions/3062100/piping-to-findstrs-input

Maybe try just `ps4-waker -b 10.0.0.31 search | findstr 200`

**Comment by MarkieMark96** [comment]
"ps4-waker -b 10.0.0.31 search | findstr 200" registers the PS4 as always off so I presume this isn't working as intended but it will turn the PS4 on successfully and then switch the 'switch' in HomeKit back to off.

Whilst not perfect this is far better than having it as "always on" and I never have a need to turn it off via HomeKit so this works for me at least.

Thank you for your help, any way people can throw a couple bucks your way for what you have made here? Paypal donation or something?

**Comment by dhleong** [comment]
@MarkieMark96 Give 1.7.0 a shot! Use something like `ps4-waker -b 10.0.0.31 check`

**Comment by MarkieMark96** [comment]
I can confirm this is working perfectly so far! Thank you very much

**Comment by dhleong** [comment]
No problem!
