### ISSUE TITLE
Note on the latest 6.71 PS4 Firmware & issues

### ISSUE THREAD

**Issue by erew123** [dhleong/ps4-waker#121]
Hi

Just a friendly note... Since the 6.71 update on the PS4 a week or so ago, I think the module inside the PS4 that deals with the "PS4 Companion App" may be problematic. This I think is a S-O-N-Y issue and not a PS4-Waker issue.

The long and short of the problem is that when my PS4 has been on a while (problem occurs anything from 10 minutes to 1+ hours).... all of a sudden I cant use PS4-Waker or the companion app on my phone. 

I have no network problems, the PS4 is still working and can use the internet, so its not that. I can rest and wake the PS4, but that doesnt seem to fix it.... the only thing that works is rebooting the PS4.

Im guessing S-O-N-Y will release another firmware update (they released 2 updates in about 4 days... 6.70 and 6.71).

Thought Id put it up here so you developers know and anyone who is passing by github.

Thanks

**Comment by dhleong** [comment]
Thanks for the heads up!

**Comment by dhleong** [comment]
I just briefly tested on 6.72 and things seemed to work as expected. Can anybody confirm that this issue has been resolved?

**Comment by erew123** [comment]
Seems to work fine for me on 6.72.... so I think resolved.

**Comment by dhleong** [comment]
Thanks @erew123 ! Feel free to comment if you run into it again and I'll re-open.

**Comment by Stooovie** [comment]
> Seems to work fine for me on 6.72.... so I think resolved.

Could you please post your config.json (of course without sn)? I can't get it to work. Thanks.

**Comment by dhleong** [comment]
@Stooovie Unless your issue is related to the 6.71 firmware you should probably open a new issue. For what it's worth, ps4-waker doesn't have a config.json; the credentials json file is very minimal and shouldn't need hand-editing—omitting the actual credential would just be something like `{"client-type":"a","auth-type":"C"}` which is unlikely to be helpful for you.

If what you're trying to do specifically involves `config.json` then it's a third-party product using ps4-waker, and is unrelated. This repository is for the `ps4-waker` command line program and node.js library. If either of those don't work, please post a new issue with the specific error messages and more context about your network setup.

**Comment by Stooovie** [comment]
Sorry, homebridge ps4 waker plugin Readme linked here. Thanks.
