### ISSUE TITLE
Is there an option to turn off a ps4?

### ISSUE THREAD

**Issue by thevickypedia** [dhleong/ps4-waker#149]

**Comment by dhleong** [comment]
Per the `--help` information in the README there is `ps4-waker standby` to put it to sleep. 

If you're asking to completely turn off the PS4, no, that is not possible—otherwise, there would be no way to turn it back on again remotely. As a general rule, try to do what you want to do through the official app; if that cannot do it, there is no way for this library to do it either. If it can, feel free to request it here; I make no guarantees on implementation timelines since I'm quite busy these days but I do keep an eye on this repo and pick at things every no wand then :)
