### ISSUE TITLE
Issue with dependency chain in Node 4.4.4 - ursa

### ISSUE THREAD

**Issue by benburkhart1** [dhleong/ps4-waker#18]
Using NodeJS v4.4.4, your dependency, ursa, is broken. It currently has no maintainer, and its Issues section on GitHub is filled with people no longer able to get it working in modern versions of NodeJS. It seems like your usage of it is pretty trivial, have you considered replacing it with a full JS implementation?

**Comment by dhleong** [comment]
That's something I'd prefer to have in a dependency ("don't reinvent the wheel" and all that) but if there's one you recommend, I'm not opposed to switching to something that's better maintained and known to work. I wasn't aware of the problems with ursa! 

I'm not currently at home with my dev machine, so you're welcome to work on a pull request of you like. Otherwise, I can look into it when I get back in a week or so.

**Comment by benburkhart1** [comment]
https://github.com/dhleong/ps4-waker/pull/19

**Comment by benburkhart1** [comment]
I wasn't meaning your own implementation of RSA when I said that. I was merely suggesting using something that doesn't require bindings/compilation, and instead is written in JS. node-rsa is well-tested and in use by quite a few projects, and is almost an exact drop-in replacement in this case.

**Comment by dhleong** [comment]
Perfect :)

**Comment by dhleong** [comment]
Merged and released as 1.0.1—thanks!
