### ISSUE TITLE
Check state of PS4

### ISSUE THREAD

**Issue by mredone** [dhleong/ps4-waker#46]
Hello.

Is any chance to add small improvment to check state of ps4 (on or standby).
It will be a great improvment to home automation system like domoticz or home assistant.

Regards
Jakub

**Comment by dhleong** [comment]
What sort of state are you looking for? There's already `ps4-waker search` which returns whether it's in standby or not (among other things).

**Comment by dhleong** [comment]
With almost a month without clarification, I'm closing this issue. As mentioned above, there's `ps4-waker search` on the CLI and there's also `Device.getDeviceStatus` which can be used from JS.

Feel free to comment if there's something else you're looking for not otherwise covered by these methods, but both of those return everything (that is to say, *exactly*) what the PS4 returns to us, so....

**Comment by samw321** [comment]
Is there a way to subscribe to the state? Would be cool to have a callback when the PS4 enters standby after being on (and vice versa). I want to avoid calling `Device.getDeviceStatus` in an interval to register a state change.

**Comment by dhleong** [comment]
> Is there a way to subscribe to the state? Would be cool to have a callback when the PS4 enters standby after being on (and vice versa). I want to avoid calling `Device.getDeviceStatus` in an interval to register a state change.

Off the top of my head, not really. If you have an open connection the `Device` will emit `disconnected` if the connection dies, but we don't "watch" device status in any way at the moment outside of maintaining an active connection.
