### ISSUE TITLE
Logout and Login as other user Pin required

### ISSUE THREAD

**Issue by jef99** [dhleong/ps4-waker#57]
Hello and thanks for this good code that switch on/off the Ps4

As the title say's when I log in to the ps4 primary account (ps4 connection app account) I can use fine the ps4-waker But when I logout and login as my brothers account it wont work and it will ask for PIN
I tried to enter the PIN on settings>ps4 app connection settings screen but it will still ask for a PIN like it is
wrong. In the original ps4 app I can login wherever I want even if only my bother has logged in the ps4 , how can I make it work ? 
Please a little bit of help 

Cheers

**Comment by dhleong** [comment]
I've never tested this use case, but you probably need to use two separate credentials files. See: https://github.com/dhleong/ps4-waker/wiki#credentials

**Comment by dhleong** [comment]
Glad it's working for you!

It would be possible, but I don't see the benefit. Either way you're passing arguments to the command line. It'd be the difference between:

    ps4-waker -c user1.json

and:

    ps4-waker -u user1

In fact, the separate files mechanism is slightly more convenient since, on most shells, you get file path tab-completion for free. 

Since it is working for you and the only difference explicit user support would provide is a slightly different syntax, I'm disinclined to add extra complexity to the code base.
