### ISSUE TITLE
How to setup

### ISSUE THREAD

**Issue by borinbilly** [dhleong/ps4-waker#67]
How do you set this up?
I have ps4-waker installed on my pc, second screen on my phone is paired with my ps4.
However, when i run "ps4-waker" in my windows powershell it returns "Could not detect any matching PS4 device."
I beleive it is because i have multiple network adapters, but i do not know how to specify which one to use, using the --bind argument as the PS4 i am trying to use is connected through a bridge adapter.

**Comment by dhleong** [comment]
From the wiki:

> ## The machine you're running on has multiple network adapters
> The system will just "pick" one in this case, and it might not be the one you need. Use the --bind command line option to specify the address of the appropriate adapter. This must be the same adapter that your phone can see (at least for the first run, when getting credentials from the mobile app) as well as the one that can see your PS4.

More technical: there's a combination of TCP and UDP communication going on, and there's a three-way handshake where ps4-waker tries to connect to a device and, if it needs credentials, requests them. At this point you use the phone app to connect to ps4-waker, which acts like it's a PS4 in order to get your phone's credentials, after which it can then act like your phone to talk to the PS4.

See also: https://github.com/dhleong/ps4-waker/wiki/Troubleshooting#your-network-is-dropping-udp-packets

**Comment by borinbilly** [comment]
I opened ports 987 997 and a used the bind command to force it to a third open port, but it still did not work I also disabled all network adapters except for the network that the PS4 and phone are on.

**Comment by dhleong** [comment]
I'm not sure what you mean by using bind to force open a port. You should
pass the IP address of the adapter you want to use to the bind flag, that's
it. If you have disabled all but one adapter, you shouldn't need bind at
all, I would think.

When you say "still doesn't work" does that mean ps4-waker still doesn't
see the Playstation?
