### ISSUE TITLE
Having issues installing

### ISSUE THREAD

**Issue by MaxHasADHD** [dhleong/ps4-waker#78]
So I'm installing this on a raspberry pi to get working with Homebridge through https://github.com/luisiam/homebridge-cmdswitch2, but I'm having trouble installing PS4-waker. 

First off, after installing trough `npm install -g ps4-waker`, `ps4-waker` gives me error `command not found`. I find it in `/opt/node/bin` and run it from there and get ```-bash: ps4-waker: line 3: syntax error near unexpected token `('
-bash: ps4-waker: line 3: `var {Detector, Device, Socket} = require('../')'```

I see this error in the troubleshooting page, and that it means I have a older version of node it says, but node isn't updating to anything newer for me.

Not sure which is helpful but I see `node -v v6.9.5` and `nodejs -v v4.8.2`. Any help is appreciated.

**Comment by dhleong** [comment]
Something is wonky with your node installation. If you look closely, it's
actually bash that's complaining about the syntax error, which means it's
not being run by node. If you pass the ps4-waker path to `node` instead of
calling it directly, it'll work.

But the fact that the exe wasn't available when you installed globally is
definitely a concern. I don't have a pi so can't help you specifically, but
I'd definitely consider reinstalling node.
