### ISSUE TITLE
Login error: PIN_IS_NEEDED when different user is logged in

### ISSUE THREAD

**Issue by ArturSzymiec** [dhleong/ps4-waker#80]
Hi, 

there seems to be a problem with ps4-waker that after successful pairing on one account,
where wakeup and standby commands are 100% working, when different user signs in
the same commands are not working anymore. ps4-waker gives an error PIN_IS_NEEDED.

Why is that ? Can this be fixed ?

Kind regards

Artur

**Comment by dhleong** [comment]
I've no personal experience with this situation and haven't heard of this issue before, but if you could answer some clarifying questions maybe we can get some answers:

1. Are you using the `ps4-waker` CLI app, or with a persistent connection via the NodeJS library?
1. Are you using `ps4-waker` with the second user, or do you mean they login to the PS4 directly?
1. If you're trying to use `ps4-waker` with both users, is it from the same computer? If so, are you using the `-c` flag to pick unique credentials files for each user?
1. When you say the commands don't work, do you mean for the first user, or the new user?
1. Can you give me step-by-step instructions to reproduce this?

I have a suspicion that your answer to 3. is "yes" and 4. is "the first user doesn't work, but the new user does." If that's the case then my guess is that, because PS4-Waker uses the same "device name" when registering with the PS4, that the new user registering will *replace* the first user's registration, making it no longer valid. If this is indeed what's happening, I could add a new flag that lets you specify what name PS4-Waker should register with....

**Comment by ArturSzymiec** [comment]
Hi, here are my answers to your questions:
1) Yes I'm using ps4-waker inside bash shell
2) I've paired the ps4-waker on particular user account. In my PS4 system I've got 4 different users.
3) No I'm not using the -c flag - because I don't have another credentials files
4) The standby command is working only when the user on which account pairing was executed
    is actually logged in. It doesn't work if any other user is logged in
5) Steps to reproduce:
- pair ps4-waker on particular user account
- log in to different PS4 account
- try to send standby command by ps4-waker

Yes for me it looks exactly like this - the credentials are valid only for user on which account the
pairing took place. However it's impossible to pair it again on different user account - the ps4-waker
is already on the paired devices list on PS4 for every user not just the account on which pairing
took place thus adding it twice is impossible.
Question -  if ps4-waker is on the list of allowed devices why the command from ps4-waker need
 credentials for each user ?

**Comment by dhleong** [comment]
The PS4-Waker registration is attached to a specific account, so presumably
if you're logged into a different account the PS4 will only let that
account control it. I haven't tested this though.

Have you tried using the Playstation app directly in this use case?

**Comment by iharosi** [comment]
Hi guys,

I've experienced the same issue and here is what I've found:

I'm using ```ps4-waker``` with the ```-c``` option on a Raspberry Pi on the same network with PS4.
My PS4 user has a passcode and – I assume because of this – ```ps4-waker``` can't log this user in automatically instead it drops the error: ```Login error: PIN_IS_NEEDED```, however it can wake the PS4 which stucks at the welcome screen (**Press the PS button to use the controller**).
1. if I leave the PS4 on the welcome screen – so I won't log in neither one of my user accounts –, ```ps4-waker``` can't put PS4 into standby instead drops the error: ```Login error: PIN_IS_NEEDED```
1. if I log in with my – already paired – user, ```ps4-waker``` **can** put PS4 into standby
1. if I remove my user's passcode ```ps4-waker``` works like a charm and it can put PS4 into standby from the welcome screen and even it works when I logged in with a different user

I assume ```ps4-waker``` can't pass user's passcode (yet? :D).
Hope it helps.

**Comment by dhleong** [comment]
Yep, that's right! I haven't had time to look into user pin code support
yet.

**Comment by dhleong** [comment]
Hey everyone, sorry it's been so long, but I've started using my PS4 a bit more recently and was able to find some time so I went ahead and added this in version 1.5.0. It turns out the `PIN_IS_REQUIRED` error was a misunderstanding on my part, and this feature is actually called "passcode," which probably caused some of the confusion.

Anyway, you can now use the `--pass` command line flag to provide your passcode when logging in!
