### ISSUE TITLE
ps4 switch stopped working after adding new switches

### ISSUE THREAD

**Issue by mreassassin** [dhleong/ps4-waker#84]
It was all working!  then I added a few switches for xbox's.  now the ps4-waker seems to have stopped working for some reason.  Here's how I had it setup using cmdswitch2 with homebridge (I've tried a few things with no success, like binding to adapter.):

`{
					"name": "PS4",
					"on_cmd": "sudo ps4-waker -d 192.168.1.42",
					"off_cmd": "sudo ps4-waker -d 192.168.1.42 standby",
					"state_cmd": "",
					"polling": true,
					"interval": 5,
					"timeout": 2000,
					"manufacturer": "Sony Corporation",
					"model": "CUH-1001A",
					"serial": "xxxxxxxxxxx"
				}`

here's what I get when I try to run the commands:
`
pi@raspberrypi:~ $ sudo ps4-waker -d 192.168.1.42 standby
Could not detect any matching PS4 device
pi@raspberrypi:~ $ sudo ps4-waker -d 192.168.1.42
Could not detect any matching PS4 device
pi@raspberrypi:~ $ sudo ps4-waker -d 192.168.1.42 standby
Could not detect any matching PS4 device
`

not sure how adding the extra switches could have killed it.

any ideas?

**Comment by dhleong** [comment]
Were the xbox's new to the network? If you did not assign a static IP to the PS4 it's possible its IP address changed. Have you tried running `ps4-waker search`?

**Comment by mreassassin** [comment]
the xbox's are not new to the network.  I did assign a static IP to the PS4 as well as the xbox's, previously.   they are all solid.  ps4-waker search also comes back with 
`pi@raspberrypi:~ $ ps4-waker search
Could not detect any matching PS4 device
`

**Comment by dhleong** [comment]
Odd. I'm afraid I don't know anything about cmdswitch2 or homebridge, so I
don't know what interactions they could possibly have with ps4-waker. I
assume you've tried removing the "switches" for the xbox devices to see if
reverting the change restores working behavior?

Does the raspberry pi have multiple network adapters?

**Comment by dhleong** [comment]
Try `npm uninstall -g ps4-waker` and delete the `~/.ps4-wake.credentials.json` file (or rename it/move it elsewhere). 

Does the pi have multiple network adapters, though? If so, it's possible that `ps4-waker` is listening for responses from the device on the wrong one. 

If that's not the case, it's possible that the port it's listening on is blocked somewhere along that chain of routers. See https://github.com/dhleong/ps4-waker/wiki/Troubleshooting#ps4-waker-cant-see-the-ps4

**Comment by mreassassin** [comment]
how do i find out if my pi has multiple network adapters?

I've tried binding the port also.  how could I test this?  would it make sense that I can still ping the ps4's ip?

**Comment by mreassassin** [comment]
pi@raspberrypi:~ $ ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.20  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::a5f2:1129:760c:8112  prefixlen 64  scopeid 0x20<link>
        ether b8:27:eb:0c:6c:b5  txqueuelen 1000  (Ethernet)
        RX packets 7152118  bytes 879530718 (838.7 MiB)
        RX errors 0  dropped 2099  overruns 0  frame 0
        TX packets 2464810  bytes 976637853 (931.3 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 80641  bytes 99406965 (94.8 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 80641  bytes 99406965 (94.8 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.28  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::3f33:5a2e:7cf4:29a3  prefixlen 64  scopeid 0x20<link>
        ether b8:27:eb:59:39:e0  txqueuelen 1000  (Ethernet)
        RX packets 1694880  bytes 687040102 (655.2 MiB)
        RX errors 0  dropped 1530  overruns 0  frame 0
        TX packets 9611  bytes 1192070 (1.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


It does look like there’s more than one IP. 

what can I try from here?

**Comment by mreassassin** [comment]
I've tried -b to each ip address.  no dice.  i've tried uninstalling and reinstalling.. no dice.

when i install i have to use 'sudo' is that bad?

if i don't use sudo it says I don't have permissions.  I tried changing the 'write' permissions through FileZilla but that didn't help either...  how was it working before and now it's not?

**Comment by mreassassin** [comment]
also .ps4-wake.credentials.json does not seem to exist on my pi?  how is that possible?

**Comment by dhleong** [comment]
I don't have a pi but must users posting on here with one have used sudo. If you don't want to use sudo to install ps4-waker, you can set up npm to not require it: 

https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md

When running the initial setup, you have to use sudo, because non-root users typically don't have permission to listen to the ports required. In this case, it seems the `.ps4-wake.credentials.json` ends up at `/root/.ps4-wake.credentials.json`. Some users have had success simply deleting the file and trying again, while others have success moving it out of `/root`, changing its permissions, and simply running `ps4-waker` without `sudo`. 

I don't use FileZilla but because the filename is prefixed with a `.` it's possible that FileZilla doesn't show it. 

This is probably a routing issue, and the Xboxes are probably a red herring—it sounds like you have a fairly complicated network setup. You want to make sure that you have port forwards set up for the ports mentioned [here](https://github.com/dhleong/ps4-waker/wiki/Troubleshooting#your-network-is-dropping-udp-packets). It looks like your pi is connected to your network over wifi (the `wlan0` device) in addition to the other routes you mentioned. Since your phone will need to see it for the initial setup, you probably want to bind to that adapter (`-b 192.168.1.28`). You might also try explicitly specifying the PS4's IP address with the `-d` flag. If you are explicitly binding to the wifi adapter, make sure whatever wifi router your pi is attached to also has a route to the PS4.

You can use the `-S` flag with `ping` to specify a specific network adapter to use.

**Comment by mreassassin** [comment]
still getting this:

pi@raspberrypi:~ $ sudo ps4-waker -d 192.168.1.42 -b 192.168.1.28
Could not detect any matching PS4 device

putty also tells me it the credentials.json file doesn't exist.  how can I create it from scratch?  or how could i open it through putty?

**Comment by dhleong** [comment]
How are you looking for it? Try `sudo ls -al /root`

I'm not sure what else to suggest other than hooking your ps4 directly to
the same router that the pi is connected to and seeing what happens.

**Comment by mreassassin** [comment]
I created it using nano but couldn’t place it in the root folder. Any way to change the permissions through putty?

pi@raspberrypi:~ $ sudo ls -al /root
total 48
drwx------  9 root root 4096 Aug 18 14:32 .
drwxr-xr-x 22 root root 4096 Aug 18 14:28 ..
-rw-------  1 root root  148 Jul  8 02:28 .bash_history
-rw-r--r--  1 root root  570 Mar 12 07:03 .bashrc
drwx------  3 root root 4096 Jul  8 02:37 .cache
drwx------  3 root root 4096 Jul  2 21:11 .config
drwxr-xr-x  3 root root 4096 Jul  8 03:34 .homeassistant
drwxr-xr-x  4 root root 4096 Jul  8 04:37 .homebridge
drwxr-xr-x  2 root root 4096 Jul  8 02:40 .nano
drwxr-xr-x  3 root root 4096 Jul  2 21:11 .node-gyp
drwxr-xr-x  6 pi   pi   4096 Jul  8 04:06 .npm
-rw-r--r--  1 root root  148 Mar 12 07:03 .profile
-rw-r--r--  1 root root    0 Aug 18 14:32 .ps4-wake.credentials.json
pi@raspberrypi:~ $

**Comment by mreassassin** [comment]
I don't know how to open up ports on my router.  i have a d-link DIR-825.  I found the 'virtal servers' section.  do i input the ip of the ps4 and open up the ports? how do I ensure my router will let through UDP packets to/from port 987 and 997 on the PS4?
