### ISSUE TITLE
osk-submit doesn't escape $ characters

### ISSUE THREAD

**Issue by beaumartinez** [dhleong/ps4-waker#92]
Trying to submit text with $ in them doesn't work.

Anything after $ gets ignored, so if you send ABC$HELLO, it only sends ABC.

Curiously sending $$ sends 70782, I don't know the significance of that.

As a workaround you can escape $ with a \ before it, so sending `ABC\$HELLO` does send ABC$HELLO.

FYI the module responsible is `packets.js`.

**Comment by dhleong** [comment]
I believe this is just your terminal / shell. The $ character is the start
of a variable in most shells, and I believe $$ is the process ID or
something. You can prevent variable substitution by wrapping the argument
in single quotes, or by prefixing the $ with a \ as you have discovered.
Since the shell is doing this, ps4-waker can't do anything about it,
unfortunately.

**Comment by beaumartinez** [comment]
That entirely slipped my mind. I thought using double quotes would be enough to escape them. Thanks @dhleong.

**Comment by dhleong** [comment]
No problem! For future reference, double quotes group together a single
argument but do not prevent variable interpolation.
